# Generated by Django 5.1.3 on 2025-04-05 14:30
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='phi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='psi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structure',
            name='structure',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
