# Generated by Django 5.1.3 on 2025-04-05 16:10
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_phi_alter_card_psi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='phi',
        ),
        migrations.RemoveField(
            model_name='card',
            name='psi',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='structure',
        ),
        migrations.AddField(
            model_name='card',
            name='res1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='res2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='structure_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
