# Generated by Django 5.1.3 on 2025-04-06 10:44
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_phi_remove_card_psi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=54)),
                ('answer', models.CharField(max_length=16)),
            ],
        ),
    ]
