# Generated by Django 5.1.3 on 2025-04-05 09:05
# pylint: disable=all

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=100)),
                ('pdb', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phi', models.IntegerField(verbose_name=4)),
                ('psi', models.IntegerField(verbose_name=4)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.structure')),
            ],
        ),
    ]
