# Generated by Django 5.1.3 on 2025-04-07 15:13
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleotide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('answer1', models.CharField(max_length=1)),
                ('answer2', models.CharField(max_length=30)),
            ],
        ),
    ]
